//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_Character_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DnD_Character" +
            "_ManagerDB.mdf;Integrated Security=True")]
        public string DnD_Character_ManagerDBConnectionString {
            get {
                return ((string)(this["DnD_Character_ManagerDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=D:\\CODE\\VISUALSTUDIO\\_PROJECTS" +
            "\\DND_CHARACTER_MANAGER\\DND_CHARACTER_MANAGER\\BIN\\DEBUG\\DND_CHARACTER_MANAGERDB.M" +
            "DF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertific" +
            "ate=True")]
        public string D__CODE_VISUALSTUDIO__PROJECTS_DND_CHARACTER_MANAGER_DND_CHARACTER_MANAGER_BIN_DEBUG_DND_CHARACTER_MANAGERDB_MDFConnectionString {
            get {
                return ((string)(this["D__CODE_VISUALSTUDIO__PROJECTS_DND_CHARACTER_MANAGER_DND_CHARACTER_MANAGER_BIN_DE" +
                    "BUG_DND_CHARACTER_MANAGERDB_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=D:\\CODE\\VISUALSTUDIO\\_PROJECTS" +
            "\\DND_CHARACTER_MANAGER\\DND_CHARACTER_MANAGER\\BIN\\RELEASE\\DND_CHARACTER_MANAGERDB" +
            ".MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertif" +
            "icate=True")]
        public string D__CODE_VISUALSTUDIO__PROJECTS_DND_CHARACTER_MANAGER_DND_CHARACTER_MANAGER_BIN_RELEASE_DND_CHARACTER_MANAGERDB_MDFConnectionString {
            get {
                return ((string)(this["D__CODE_VISUALSTUDIO__PROJECTS_DND_CHARACTER_MANAGER_DND_CHARACTER_MANAGER_BIN_RE" +
                    "LEASE_DND_CHARACTER_MANAGERDB_MDFConnectionString"]));
            }
        }
    }
}
